# Generated by Django 5.2 on 2025-04-17 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('nexmo', 'Nexmo/Vonage'), ('aws_sns', 'AWS SNS')], default='twilio', max_length=20)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nexmo_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('nexmo_api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('nexmo_from_name', models.CharField(blank=True, max_length=20, null=True)),
                ('aws_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_region', models.CharField(blank=True, max_length=20, null=True)),
                ('aws_sender_id', models.CharField(blank=True, max_length=20, null=True)),
                ('use_custom_sms', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_config', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('verification', 'Verification Code'), ('welcome', 'Welcome Message'), ('password_reset', 'Password Reset')], max_length=20)),
                ('recipient', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('verification', 'Verification Code'), ('welcome', 'Welcome Message'), ('password_reset', 'Password Reset')], max_length=20)),
                ('content', models.TextField(help_text='Use {{placeholder}} syntax for dynamic content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'template_type')},
            },
        ),
    ]
