# Generated by Django 5.2 on 2025-04-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_type', models.CharField(choices=[('smtp', 'SMTP Server'), ('sendgrid', 'SendGrid API'), ('mailgun', 'Mailgun API'), ('postmark', 'Postmark API'), ('ses', 'Amazon SES')], default='smtp', max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for SendGrid, Mailgun, Postmark, etc.', max_length=255, null=True)),
                ('domain', models.CharField(blank=True, help_text='Domain for Mailgun or region for Amazon SES', max_length=255, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('use_custom_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('verification', 'Verification Code'), ('password_reset', 'Password Reset')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('verification', 'Verification Code'), ('password_reset', 'Password Reset')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use {{placeholder}} syntax for dynamic content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'template_type')},
            },
        ),
    ]
