# Generated by Django 5.2 on 2025-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for SendGrid, Mailgun, Postmark, Brevo, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='backend_type',
            field=models.CharField(choices=[('smtp', 'SMTP Server'), ('sendgrid', 'SendGrid API'), ('mailgun', 'Mailgun API'), ('postmark', 'Postmark API'), ('ses', 'Amazon SES'), ('brevo', 'Brevo API')], default='smtp', max_length=20),
        ),
    ]
